[package]
name = "rt-model"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.19"
dashmap = "6.1.0"
thiserror = "2"
num_enum = "0.7.4"
class-file = { path = "../class-file" }
common = { path = "../common" }