# Classes to extract from jdk for testing purposes
[modules."java.base"]
classes = [
    # java.lang
    "java.lang.Object",
    "java.lang.String",
    "java.lang.StringCoding",
    "java.lang.String$CaseInsensitiveComparator",
    "java.lang.StringLatin1",
    "java.lang.StringConcatHelper",
    "java.lang.StringBuilder",
    "java.lang.AbstractStringBuilder",
    "java.lang.System$1",
    "java.lang.System",
    "java.lang.System$In",
    "java.lang.System$Out",
    "java.lang.System$Err",
    "java.lang.Class",
    "java.lang.Byte",
    "java.lang.Float",
    "java.lang.Number",
    "java.lang.Integer",
    "java.lang.Integer$IntegerCache",
    "java.lang.AssertionError",
    "java.lang.Error",
    "java.lang.Throwable",
    "java.lang.Exception",
    "java.lang.RuntimeException",
    "java.lang.NullPointerException",
    "java.lang.IndexOutOfBoundsException",
    "java.lang.StackTraceElement",
    "java.lang.Math",
    "java.lang.Double",
    "java.lang.VersionProps",
    "java.lang.Runtime",
    "java.lang.InternalError",
    "java.lang.VirtualMachineError",
    "java.lang.IllegalArgumentException",
    "java.lang.Terminator",
    "java.lang.Terminator$1",
    # java.io
    "java.io.FileInputStream",
    "java.io.BufferedInputStream",
    "java.io.FilterInputStream",
    "java.io.InputStream",
    "java.io.FileDescriptor",
    "java.io.FileDescriptor$1",
    "java.io.FileOutputStream",
    "java.io.BufferedWriter",
    # java.nio
    "java.nio.ByteBuffer",
    "java.nio.Buffer",
    "java.nio.Buffer$1",
    "java.nio.Buffer$2",
    "java.nio.HeapByteBuffer",
    "java.nio.ByteOrder",
    "java.nio.charset.Charset",
    "java.nio.charset.CharsetEncoder",
    "java.nio.charset.CodingErrorAction",
    "java.nio.charset.spi.CharsetProvider",
    "java.nio.charset.StandardCharsets",
    "java.nio.charset.IllegalCharsetNameException",
    "java.nio.CharBuffer",
    "java.nio.HeapCharBuffer",
    "java.nio.charset.CoderResult",
    # sun
    "sun.nio.cs.StandardCharsets",
    "sun.nio.cs.StandardCharsets$Aliases",
    "sun.nio.cs.StandardCharsets$Cache",
    "sun.nio.cs.StandardCharsets$Classes",
    "sun.util.PreHashedMap",
    "sun.nio.cs.UTF_8",
    "sun.nio.cs.UTF_8$Encoder",
    "sun.nio.cs.Unicode",
    "sun.nio.cs.ISO_8859_1",
    "sun.nio.cs.US_ASCII",
    "sun.nio.cs.UTF_16BE",
    "sun.nio.cs.UTF_16LE",
    "sun.nio.cs.UTF_16",
    "sun.nio.cs.UTF_32BE",
    "sun.nio.cs.UTF_32LE",
    "sun.nio.cs.UTF_32",
    "sun.nio.cs.StreamEncoder",
    # java.io
    "java.io.PrintStream",
    "java.io.OutputStreamWriter",
    "java.io.Writer",
    "java.io.FilterOutputStream",
    "java.io.OutputStream",
    "java.io.ObjectStreamField",
    "java.io.BufferedOutputStream",
    # java.util
    "java.util.Arrays",
    "java.util.Map",
    "java.util.Map$Entry",
    "java.util.Set",
    "java.util.Iterator",
    "java.util.HashMap",
    "java.util.HashMap$KeySet",
    "java.util.HashMap$KeyIterator",
    "java.util.HashMap$EntryIterator",
    "java.util.HashMap$HashIterator",
    "java.util.HashMap$EntrySet",
    "java.util.HashMap$TreeNode",
    "java.util.HashMap$Node",
    "java.util.LinkedHashMap$Entry",
    "java.util.AbstractMap",
    "java.util.Collections",
    "java.util.Collections$EmptyList",
    "java.util.Collections$EmptySet",
    "java.util.Collections$EmptyMap",
    "java.util.AbstractSet",
    "java.util.AbstractCollection",
    "java.util.AbstractList",
    "java.util.Properties",
    "java.util.Hashtable",
    "java.util.Hashtable$Entry",
    "java.util.Objects",
    "java.util.Dictionary",
    "java.util.concurrent.ConcurrentHashMap",
    "java.util.concurrent.ConcurrentHashMap$ReservationNode",
    "java.util.concurrent.ConcurrentHashMap$CounterCell",
    "java.util.concurrent.ConcurrentHashMap$Node",
    "java.util.concurrent.locks.LockSupport",
    # internal
    "jdk.internal.util.StaticProperty",
    "jdk.internal.util.SystemProps",
    "jdk.internal.util.SystemProps$Raw",
    "jdk.internal.util.ArraysSupport",
    "jdk.internal.util.Preconditions",
    "jdk.internal.util.Preconditions$1",
    "jdk.internal.util.Preconditions$2",
    "jdk.internal.util.Preconditions$3",
    "jdk.internal.util.Preconditions$4",
    "jdk.internal.util.DecimalDigits",
    "jdk.internal.misc.Unsafe",
    "jdk.internal.misc.UnsafeConstants",
    "jdk.internal.misc.VM",
    "jdk.internal.misc.ScopedMemoryAccess",
    "jdk.internal.misc.Signal",
    "jdk.internal.misc.Signal$Handler",
    "jdk.internal.misc.Signal$NativeHandler",
    "jdk.internal.misc.OSEnvironment",
    "jdk.internal.misc.CDS",
    "jdk.internal.misc.Blocker",
    "jdk.internal.access.JavaLangRefAccess",
    "jdk.internal.access.JavaLangAccess",
    "jdk.internal.access.SharedSecrets",
    "jdk.internal.access.JavaIOFileDescriptorAccess",
]
